version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "50000:50000"
    volumes: ['./app:/app']



  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
